package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.CommandPS5Controller;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.commands.StrategyManager;
import frc.robot.generated.FieldConstants;
import frc.robot.generated.TargetType;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.LimelightHelpers.PoseEstimate;
import frc.robot.util.HubLogic;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    public double rot180;
    public double shooterspeed;
    public int checkcase = 0;
    public boolean wonAuto;
    double LensHeight = 13;
    double goalHeight = 2.955;
    double offsetAngleVertical;
    double distance;
    double tx, ty;
    boolean DetectedFuel;
    Command followCommand = null;
    private Rotation2d overrideRot;
    public Command pathfindingCommand;
    public boolean pathDone;
    // ShooterCalc shooterCalc;
    public boolean LimSeed = false;
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    public double calcdist;
    LimelightHelpers.PoseEstimate mt2 = new PoseEstimate();
    LimelightHelpers.PoseEstimate lim2mt2 = new PoseEstimate();
    boolean rejectUpdate;
    boolean rejectUpdate2;
    public double ReqRot;
    public double FinalError;
    public double HubX = FieldConstants.BlueHubX; // 11.935; //
    public double HubY = FieldConstants.BlueHubY;// 4.024;// 4.024; //
    private final double BumpX1 = 14.2;
    private final double BumpX2 = 10.4;
    private final double BumpY1 = 4.80;
    private final double BumpY2 = 6.120;
    private double lastrotDrive;
    public double rotDrive;
    public double Rot45;
    public double LastRot45 = 0;
    public double Error45;
    public double xOdo;
    public double yOdo;
    public double rot;
    public double LastReqRot = 0;
    public double LastError180 = 0;
    public double Heading;
    public double Error;
    public double Error180;
    private double limit;
    private double angle=0;
    double reqAngle;
    private CommandPS5Controller User1 = new CommandPS5Controller(0);
    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();
    private double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond);
    boolean Alliances;

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {

        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide cyonstants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configureAutoBuilder();

        SmartDashboard.putString("CurrentShift ", HubLogic.getCurrentShift());
        SmartDashboard.putBoolean("HubActive", HubLogic.isMyHubActive());
        SmartDashboard.putNumber("ShiftTime", HubLogic.getShiftTimeRemaining());
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                    () -> getState().Pose, // Supplier of current robot pose
                    this::resetPose, // Consumer for seeding pose against auto
                    () -> getState().Speeds,
                    // Supplier of current robot speeds
                    // Consumer of ChassisSpeeds and feedforwards to drive the robot
                    (speeds, feedforwards) -> setControl(
                            m_pathApplyRobotSpeeds.withSpeeds(speeds)
                                    .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                                    .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
                    new PPHolonomicDriveController(
                            // PID constants for translation
                            new PIDConstants(5, 0, 0),
                            // PID constants for rotation
                            new PIDConstants(5, 0, 0)),
                    config,
                    // Assume the path needs to be flipped for Red vs Blue, this is normally the
                    // case

                    () -> false,
                    this // Subsystem for requirements

            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder",
                    ex.getStackTrace());
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override

    public void periodic() {
        //   if (DriverStation.getAlliance().get()==Alliance.Red){
        //  angle = Math.toDegrees(Math.atan2(User1.getRightX(), User1.getRightY()));
        //   }
        // else {
        //  angle = Math.toDegrees(Math.atan2(-User1.getRightX(), -User1.getRightY()));
        // }

        //DO NOT CHANGE
        double dist = Math.hypot(-User1.getRightY(), User1.getRightX());
        // angle = (angle + 360) % 360;
            reqAngle = angle;
        

        double driveError = reqAngle - GetHeading();
        if (angle>0)
        driveError = (driveError + 180) % 360 - 180;
        else {
            driveError = (driveError - 180) % 360 + 180;
        }
        if (dist>1){
            limit=1;
        }else {
            limit = dist;
        }
        if (Math.abs(driveError) > 2 && dist> 0.1) {
             rotDrive = (0.05 * driveError) + (0.001 * ((driveError - lastrotDrive) / 0.02));
            lastrotDrive = driveError;
            rotDrive = Math.max(-limit, Math.min(rotDrive, limit));
        } else {
            rotDrive = 0;
        }

        calcdist = Math.sqrt((((HubX - xOdo) * (HubX - xOdo)) + ((HubY - yOdo) * (HubY - yOdo))));

        LimelightHelpers.SetRobotOrientation("limelight-l", GetHeading(), 0, 0, 0, 0, 0);
        // if (DriverStation.isAutonomousEnabled()){
        // if (DriverStation.getAlliance().get() == Alliance.Red)
        // mt2 = LimelightHelpers.getBotPoseEstimate_wpiRed_MegaTag2("limelight-l");
        // if (DriverStation.getAlliance().get() == Alliance.Blue)
        // mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-l");
        // }else {
        mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-l");

        rejectUpdate = false;

        // ✅ 4. Normal rejection rules (only used BEFORE auto, or in teleop)
        if (mt2 == null || mt2.tagCount == 0) {
            rejectUpdate = true;
        }

        if (Math.abs(getPigeon2().getAngularVelocityZDevice().getValueAsDouble()) > 720) {
            rejectUpdate = true;
        }

        // 5. Apply MT2 once vision is enabled

        // We trust X/Y but ignore
        if (!rejectUpdate) {
            setVisionMeasurementStdDevs(VecBuilder.fill(0.7, 0.7, 9999999));
            addVisionMeasurement(mt2.pose, mt2.timestampSeconds);
        }

        // ✅ 6. Dashboard

        SmartDashboard.putNumber("Vision X", (mt2 != null) ? mt2.pose.getX() : -99);
        SmartDashboard.putNumber("Vision Y", (mt2 != null) ? mt2.pose.getY() : -99);
        SmartDashboard.putNumber("Robot X", getState().Pose.getX());
        SmartDashboard.putNumber("Robot Y", getState().Pose.getY());
        SmartDashboard.putNumber("Heading", GetHeading());
        SmartDashboard.putNumber("Degrees Required", ReqRot);
        SmartDashboard.putNumber("Error", Error);
        SmartDashboard.putNumber("Dist", calcdist);
        SmartDashboard.putNumber("Shooter Speed", shooterspeed);
        SmartDashboard.putNumber("Joystick heading",angle);
        SmartDashboard.putNumber("Joystick magnitude", dist);
        SmartDashboard.putNumber("Dirvetrain rot", rotDrive);
        SmartDashboard.putNumber("Drive error", driveError);
        SmartDashboard.putString("CurrentShift ", HubLogic.getCurrentShift());
        SmartDashboard.putBoolean("HubActive", HubLogic.isMyHubActive());
        SmartDashboard.putNumber("ShiftTime", HubLogic.getShiftTimeRemaining());

        // ✅ Operator Perspective logic
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    public void autoAlignToHub() {

    if (DriverStation.getAlliance().get()==Alliance.Red) {
    HubX = FieldConstants.RedHubX;
    HubY = FieldConstants.RedHubY;
    } else {
    HubX = FieldConstants.BlueHubX;
    HubY = FieldConstants.BlueHubY;
    }

    double robotX = getState().Pose.getX();
    double robotY = getState().Pose.getY();

    TargetType type = StrategyManager.getTargetType(robotX, robotY);
    Translation2d target = FieldConstants.getTarget(type);

    Heading = getState().Pose.getRotation().getDegrees();

    ReqRot = Math.toDegrees(Math.atan2((target.getY() - robotY), (target.getX() -
    robotX)));
    ReqRot += 180;
    ReqRot = (ReqRot + 360) % 360;

    Error = ReqRot - Heading;
    Error = (Error + 180) % 360 - 180;

    if (Math.abs(Error) > 2) {
    rot = (0.05 * Error) + (0.001 * ((Error - LastReqRot) / 0.02));
    LastReqRot = Error;
    rot = Math.max(-0.5, Math.min(rot, 0.5));
    } else {
    rot = 0;
    }
    }

    // public void autoAlignToHub() {

    //     double robotX = getState().Pose.getX();
    //     double robotY = getState().Pose.getY();

    //     TargetType type = StrategyManager.getTargetType(robotX, robotY);
    //     Translation2d target = FieldConstants.getTarget(type);

    //     Heading = getState().Pose.getRotation().getDegrees();

    //     // Normal target angle
    //     ReqRot = Math.toDegrees(
    //             Math.atan2(
    //                     (target.getY() - robotY),
    //                     (target.getX() - robotX)));

    //     ReqRot += 180;
    //     ReqRot = (ReqRot + 360) % 360;

    //     // ----------------------------
    //     // 🔥 ROTATION COMPENSATION
    //     // ----------------------------

    //     double distanceMeters = Math.hypot(
    //             target.getX() - robotX,
    //             target.getY() - robotY);

    //     // Dynamic flight time

    //     double flightTime = 0.1 * distanceMeters;

    //     // Robot angular velocity
    //     double omega = getState().Speeds.omegaRadiansPerSecond;

    //     // Convert future rotation into degrees
    //     double rotationCompDeg = Math.toDegrees(omega * flightTime);

    //     // Add compensation
    //     ReqRot += rotationCompDeg;

    //     // renormalize
    //     ReqRot = (ReqRot + 360) % 360;

    //     // ----------------------------
    //     // Error calculation
    //     // ----------------------------

    //     Error = ReqRot - Heading;
    //     Error = (Error + 180) % 360 - 180;
    //     SmartDashboard.putNumber("Reqrotnot on move", ReqRot);
    //     if (Math.abs(Error) > 2) {

    //         rot = (0.05 * Error)
    //                 + (0.001 * ((Error - LastReqRot) / 0.02));

    //         LastReqRot = Error;

    //         rot = Math.max(-0.5, Math.min(rot, 0.5));

    //     } else {
    //         rot = 0;
    //     }
    // }

    public double BotHeading() {
        return getState().Pose.getRotation().getDegrees();
    }

    public boolean AutoAllign() {
        if ((Math.abs(Error) > 1)) {
            rot = (0.05 * Error) + (0.002 * ((Error - LastReqRot) / 0.02));
            LastReqRot = Error;
            rot = Math.max(-0.3, Math.min(rot, 0.3));
            return true;
        } else {
            return false;
        }

    }

    public Command CancelCommand() {
        pathfindingCommand = null;
        return pathfindingCommand;
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    public double getXPose() {
        return getState().Pose.getX();
    }

    public double getYPose() {
        return getState().Pose.getY();
    }

    public double getBackFacingTarget() {
        var alliance = DriverStation.getAlliance().orElse(DriverStation.Alliance.Blue);

        if (alliance == DriverStation.Alliance.Blue) {
            return 180; // face back
        } else {
            return 0; // red alliance → back is 0
        }
    }

    // public double getBackRotationOutput() {
    // double target = getBackFacingTarget();
    // double heading = getState().Pose.getRotation().getDegrees();

    // double error = target - heading;

    // // Normalize (-180 to 180)
    // error = (error + 180) % 360 - 180;

    // double kP = 0.08;
    // double output = kP * error;

    // return Math.max(-1, Math.min(output, 1));
    // }

    public double getBackRotationOutput() {

        double target = getBackFacingTarget();
        double heading = getState().Pose.getRotation().getDegrees();

        double error = target - heading;

        // Normalize
        error = (error + 180) % 360 - 180;

        if (error == -180) {
            error = 180;
        }

        // Stop zone
        if (Math.abs(error) < 2) {
            return 0;
        }

        double kP = 0.02;
        double kMin = 0.08;

        double output = kP * error;

        if (Math.abs(output) < kMin) {
            output = Math.signum(output) * kMin;
        }

        // clamp
        output = Math.max(-0.6, Math.min(output, 0.6));

        return output;
    }

    public double GetHeading() {
        return getState().Pose.getRotation().getDegrees();
    }

    public Pose2d GetPose() {
        return getState().Pose;
    }

    public void SetNSeed() {
        LimSeed = true;
    }

    public void rotOverride(double deg) {
        overrideRot = Rotation2d.fromDegrees(deg);
    }

    public void clearOverride(double deg) {
        overrideRot = null;
    }

    public double GetDistFromHub() {
        if (calcdist > 4) {
            return 4;
        }
        return calcdist;
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     * 
     * 
     * 
     * 
     * 
     * 
     * 
     * 
     * 
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public double mapRange(double value, double inputStart, double inputEnd, double outputStart, double outputEnd) {
        // Avoid division by zero if the input range is zero
        if (inputStart == inputEnd) {
            throw new IllegalArgumentException("Input range cannot be zero.");
        }

        // Calculate the proportion of the value within the input range
        double proportion = (value - inputStart) / (inputEnd - inputStart);

        // Apply the proportion to the output range and shift by the output start
        return outputStart + proportion * (outputEnd - outputStart);
    }

}
